true:
  issue_comment:
    types:
    - created
jobs:
  call_workflow:
    secrets: inherit
    uses: vivoblueos/kernel/.github/workflows/reusable_cross_repos_build.yml@main
name: Trigger build cross multiple repositories
