name: Trigger build cross multiple repositories
on:
  issue_comment:
    types:
      - created
jobs:
  call_workflow:
    secrets: inherit
    uses: vivoblueos/kernel/.github/workflows/reusable_cross_repos_build.yml@main
